[package]
name = "natrix"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Wenzhuo Liu"]
license = "MIT"
description = "Natrual and consistent matrix for typst."

homepage = "https://github.com/Enter-tainer/natrix"
repository = "https://github.com/Enter-tainer/natrix"
keywords = ["LaTeX", "matrix", "math", "fix"]
exclude = ["natrix.svg"]
